:_mod-docs-content-type: CONCEPT

[id="Overview-of-Hosts-in-{Project}_{context}"]
= Overview of hosts in {Project}

A host is any Linux client managed by {ProjectName}.
Hosts can be configured as physical or virtual.

Virtual hosts can be deployed on any platform supported by {ProjectName},
ifndef::satellite,orcharhino[]
such as Amazon EC2, Google Compute Engine, KVM, libvirt, Microsoft Azure, OpenStack, Proxmox, Rackspace Cloud Services, or VMware vSphere.
endif::[]
ifdef::satellite[]
such as Amazon EC2, Google Compute Engine, KVM, libvirt, Microsoft Azure, OpenStack, Rackspace Cloud Services, or VMware vSphere.
endif::[]
ifdef::orcharhino[]
such as Amazon EC2, Google Compute Engine, libvirt, Microsoft Azure, Proxmox, and VMware vSphere.
endif::[]

In {Project}, hosts can be managed at scale, including monitoring, provisioning, remote execution,
ifdef::katello,orcharhino,satellite[]
subscription management, content management,
endif::[]
and configuration management.
Hosts can also be grouped by using features such as host groups and host collections.
