[id="requirements-for-ansible-modules-connecting-to-the-{project-context}-api"]
= Requirements for Ansible modules connecting to the {Project} API

Ansible modules from the {Project} Ansible Collections must be able to communicate with the {Project} API over HTTPS.
In your playbooks, you must provide your {ProjectServer} URL and {Project} user credentials to enable the connection.

To provide the URL of your {ProjectServer}, use the `server_url` parameter:

[options="nowrap" subs="+quotes,attributes"]
----
- name: _Example playbook_
  hosts: _localhost_
  tasks:
    - name: _Ensure task is executed_
      {ansible-namespace}._module_:
        *server_url*: _https://{foreman-example-com}_
----

To provide credentials, {Project} Ansible modules support the following methods for authenticating with the {Project} API:

* User name and password
+
[options="nowrap" subs="+quotes,attributes"]
----
        *username*: _admin_
        *password*: _My_Password_
----
+
[IMPORTANT]
====
Do not store sensitive credentials, such as username and password, directly in your playbooks or environment variables.
Use a secure method for managing sensitive data, such as Ansible vault.
====
* Kerberos ticket of an {FreeIPA} user.
You can use this authentication method if your {ProjectServer} is configured to use {FreeIPA} as the authentication source

.Additional resources
ifdef::satellite[]
* For information about using Ansible vault, see {RHELDocsBaseURL}9/html-single/automating_system_administration_by_using_rhel_system_roles/index[_Automating system administration by using RHEL system roles_].
endif::[]
ifndef::satellite[]
* For information about using Ansible vault, see https://docs.ansible.com/ansible/latest/vault_guide/index.html[Protecting sensitive data with Ansible vault] in _Ansible Community Documentation_.
endif::[]
